[package]
name = "events-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Discord API
serenity = "0.12"
poise = "0.6"
tokio = { version = "1.36", features = ["macros", "signal", "rt-multi-thread", "net", "io-util"] }

# Misc
dashmap = "5.5.3"
parking_lot = "0.12.1"
serde = "1.0.198"
serde_json = "1.0.116"
